export const HOME_URL = '/'
export const LOGIN = '/login'
export const SIGNUP = '/signup'
export const SIGNUP_COMPLETE = '/signup/complete'
export const ONBOARDING = '/onboarding'
export const CHAT_PAGE = '/chat'
export const DOCUMENTS = '/documents'
export const SETTINGS = '/settings'
